name: Real Tweets to Telegram

on:
  schedule:
    - cron: '30 13 * * *'  # Every day at 16:30 Iran time (13:30 UTC)
  workflow_dispatch:

jobs:
  send-real-tweets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python main.py
